package com.votingsystem.for_reality_shows.repository;

import com.votingsystem.for_reality_shows.model.SupportTicket;
import com.votingsystem.for_reality_shows.model.TicketStatus;
import com.votingsystem.for_reality_shows.model.TicketType;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/** Database queries for tickets. Most are generated by Spring Data from the method name. */
@Repository
public interface SupportTicketRepository extends JpaRepository<SupportTicket, Long> {

    // Lookups and filters
    Optional<SupportTicket> findByTicketRef(String ticketRef);

    List<SupportTicket> findByStatus(TicketStatus status);

    List<SupportTicket> findByType(TicketType type);

    List<SupportTicket> findBySubmittedByUserId(Long userId);

    /** Finds an identical ticket from the same user created after the given time (duplicate guard). */
    Optional<SupportTicket> findFirstBySubmittedByUserIdAndSubjectAndDescriptionAndCreatedAtAfter(
            Long userId, String subject, String description, LocalDateTime after);

    List<SupportTicket> findByStatusAndType(TicketStatus status, TicketType type);

    // Counters used by the dashboard stats
    @Query("SELECT COUNT(t) FROM SupportTicket t WHERE t.status = :status")
    long countByStatus(TicketStatus status);

    long countByTypeInAndStatusNot(
            List<TicketType> types,
            TicketStatus status
    );
}
